### ISSUE TITLE
affine rasters are not correctly transformed

### ISSUE THREAD

**Issue by tsamsonov** [r-spatial/stars#131] opened 2019-03-01 11:16 UTC
It seems like affine parameters do not work as intended. I noted at least three issues:

1. Rotated rasters are scaled too
2. Rotation does not work correctly when `delta`y is positive
3. Affine parameters are dependent on `delta`s. Larger `delta`s require larger `affine` parameter values to rotate by the same angle

Here is the reprex:

``` r
library(stars)
#> Загрузка требуемого пакета: abind
#> Загрузка требуемого пакета: sf
#> Linking to GEOS 3.6.1, GDAL 2.1.3, PROJ 4.9.3

s = st_as_stars(matrix(1:16, nrow = 4, ncol = 4))
attr(s, "dimensions")[[2]]$delta = -1

s2 = s

# let's rotate the raster 45 degrees anticlockwise
attr(attr(s2, "dimensions"), "raster")$affine = c(tan(pi/4), tan(pi/4))

plot(st_as_sf(s2) %>% st_geometry(), axes = TRUE) # rotated and scaled
plot(st_as_sf(s) %>% st_geometry(), border = 'red', add = TRUE)
```

![](https://i.imgur.com/eTOIOSV.png)

``` r

# the same with a positive value of deltay
s3 = s

attr(s3, "dimensions")[[2]]$delta = 1
attr(attr(s3, "dimensions"), "raster")$affine = c(tan(pi/4), tan(pi/4))

plot(st_as_sf(s3) %>% st_geometry(), axes = TRUE) # rotated and degenerate
plot(st_as_sf(s) %>% st_geometry(), border = 'red', add = TRUE)
```

![](https://i.imgur.com/wXhOPhS.png)

``` r

# the same with a LARGE negative value of deltay not equal to -1
s4 = s

attr(s4, "dimensions")[[1]]$delta = 2
attr(s4, "dimensions")[[2]]$delta = -2
attr(attr(s4, "dimensions"), "raster")$affine = c(tan(pi/4), tan(pi/4))

plot(st_as_sf(s4) %>% st_geometry(), axes = TRUE)  # rotated SMALLER than 45
plot(st_as_sf(s) %>% st_geometry(), border = 'red', add = TRUE)
```

![](https://i.imgur.com/poLrPme.png)

``` r

# the same with a SMALL negative value of deltay not equal to -1
s4 = s

attr(s4, "dimensions")[[1]]$delta = 0.75
attr(s4, "dimensions")[[2]]$delta = -0.75
attr(attr(s4, "dimensions"), "raster")$affine = c(tan(pi/4), tan(pi/4))

plot(st_as_sf(s4) %>% st_geometry(), axes = TRUE)  # rotated LARGER than 45
plot(st_as_sf(s) %>% st_geometry(), border = 'red', add = TRUE)
```

![](https://i.imgur.com/K2Gd2iY.png)

``` r

sessionInfo()
#> R version 3.5.2 (2018-12-20)
#> Platform: x86_64-apple-darwin15.6.0 (64-bit)
#> Running under: macOS Mojave 10.14.3
#> 
#> Matrix products: default
#> BLAS: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRblas.0.dylib
#> LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib
#> 
#> locale:
#> [1] ru_RU.UTF-8/ru_RU.UTF-8/ru_RU.UTF-8/C/ru_RU.UTF-8/ru_RU.UTF-8
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#> [1] stars_0.3-0 sf_0.7-3    abind_1.4-5
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.0      class_7.3-15    digest_0.6.18   grid_3.5.2     
#>  [5] DBI_1.0.0       magrittr_1.5    units_0.6-2     e1071_1.7-0.1  
#>  [9] evaluate_0.13   highr_0.7       rlang_0.3.1     stringi_1.3.1  
#> [13] rmarkdown_1.11  tools_3.5.2     stringr_1.4.0   parallel_3.5.2 
#> [17] xfun_0.5        yaml_2.2.0      compiler_3.5.2  classInt_0.3-1 
#> [21] htmltools_0.3.6 knitr_1.21
```

<sup>Created on 2019-03-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by edzer** [comment] 2019-03-01 11:33
If you say "not as intended", do you mean "not in agreement with the two equations in [this](https://r-spatial.github.io/stars/articles/stars4.html#raster-attributes-rotated-and-sheared-grids) section"?

**Comment by tsamsonov** [comment] 2019-03-01 12:24
As I see from the vignette, affine parameters are mostly _intended_ to allow handling of rotated and sheared grids. However, they do have 'scaling' side effects (not highlighted in documentation) which in fact change the resolution of a raster. Currently, to just rotate the grid I need also to change the `deltas` manually beforehand (to compensate the scaling effect). Therefore, these affine parameters are not effective to describe the rotation/shearing of a raster in a straightforward way. If there are no other goals of introducing them rather than these two operations, I suppose that it would be more user-friendly to replace them with straight rotation angles and do all the 'affine' work behind the scenes.

**Comment by edzer** [comment] 2019-03-01 14:10
I have in mind to leave things as they are, implementation-wise, because it is closest to what GDAL does. If you have a suggestion where we could improve the documentation, or a suggestion for a helper function that computes the right parameters given a rotation and/or value, that would help.

**Comment by tsamsonov** [comment] 2019-03-01 18:02
Okay, I need some time to think over the interface and the content of such a helper function. But as of now, i think it should provide a general way to apply all kinds of affine transformations (not only rotating/shearing) to raster dimensions.

**Comment by edzer** [comment] 2019-03-19 15:09
OK; closing for now?

**Comment by tsamsonov** [comment] 2019-03-19 15:39
Yes!

**Closed** 2019-03-19 15:45 UTC

**Comment by tsamsonov** [comment] 2019-04-10 15:29
@edzer, I've just returned to this issue, and need your comment before I expose any code. According to [GDAL Data model](https://www.gdal.org/gdal_datamodel.html)

> Xgeo = GT(0) + Xpixel\*GT(1) + Yline\*GT(2)
> Ygeo = GT(3) + Xpixel\*GT(4) + Yline\*GT(5)
>
> **In case of north up images**, the GT(2) and GT(4) coefficients are zero, and the GT(1) is pixel width, and GT(5) is pixel height. The (GT(0),GT(3)) position is the top left corner of the top left pixel of the raster.

In the terms of [stars data model](https://r-spatial.github.io/stars/articles/stars4.html#raster-attributes-rotated-and-sheared-grids) it says explicitly that *GT(1) = dx* and *GT(5) = dy* for the specific case of unrotated (north-aligned) raster. To allow raster rotation without scaling we need to be able to set  GT(1) ≠ dx and GT(5) ≠ dy. As I understand, this is within the GDAL model. However, it is currently limited to setting only GT(2)  and GT(4) in `affine` element of `raster` atribute.  Are there any reasons for that?

It is possible to write a function that rotates the raster correctly, but within the current stars data model this will require to change `delta` in each spatial dimension. This is conceptually wrong, because in that case `delta` will not reflect the true raster resolution. Expanding `affine` to 4 values will allow the full specification of geotransform matrix (having in mind that GT(0) and GT(3) are taken from spatial dimension `offset`s). If this is implemented, then a raster can be rotated without altering dimensions, and writing helpers would be more straightforward too.
