### ISSUE TITLE
read_ncdf regression?

### ISSUE THREAD

**Issue by edzer** [r-spatial/stars#183] opened 2019-06-23 20:55 UTC
Trying this:
```r
library(stars)
# Loading required package: abind
# Loading required package: sf
# Linking to GEOS 3.7.0, GDAL 2.4.0, PROJ 5.2.0
f <- system.file("nc/reduced.nc", package = "stars")
read_ncdf(f)
# stars object with 4 dimensions and 4 attributes
# attribute(s):
#     sst [°C]       anom [°C]         err [°C]     ice [percent]  
#  Min.   :-1.80   Min.   :-7.950   Min.   :0.110   Min.   :0.010  
#  1st Qu.:-0.03   1st Qu.:-0.580   1st Qu.:0.160   1st Qu.:0.470  
#  Median :13.65   Median :-0.080   Median :0.270   Median :0.920  
#  Mean   :12.99   Mean   :-0.185   Mean   :0.263   Mean   :0.718  
#  3rd Qu.:24.81   3rd Qu.: 0.210   3rd Qu.:0.320   3rd Qu.:0.960  
#  Max.   :32.97   Max.   : 2.990   Max.   :0.840   Max.   :1.000  
#  NA's   :4448    NA's   :4449     NA's   :4448    NA's   :13266  
# dimension(s):
#      from  to offset delta  refsys point         values    
# lon     1 180     -1     2      NA    NA           NULL [x]
# lat     1  90    -90     2      NA    NA           NULL [y]
# zlev    1   1     NA    NA      NA    NA              0    
# time    1   1     NA    NA POSIXct    NA 1981-12-31 UTC    
read_stars(f)
# sst, anom, err, ice, 
# stars object with 4 dimensions and 4 attributes
# attribute(s):
#     sst [°C]       anom [°C]          err [°C]     ice [percent]  
#  Min.   :-1.80   Min.   :-10.160   Min.   :0.110   Min.   :0.010  
#  1st Qu.:-0.03   1st Qu.: -0.580   1st Qu.:0.160   1st Qu.:0.470  
#  Median :13.65   Median : -0.080   Median :0.270   Median :0.920  
#  Mean   :12.99   Mean   : -0.186   Mean   :0.263   Mean   :0.718  
#  3rd Qu.:24.81   3rd Qu.:  0.210   3rd Qu.:0.320   3rd Qu.:0.960  
#  Max.   :32.97   Max.   :  2.990   Max.   :0.840   Max.   :1.000  
#  NA's   :4448    NA's   :4448      NA's   :4448    NA's   :13266  
# dimension(s):
#      from  to         offset delta  refsys point values    
# x       1 180             -1     2      NA    NA   NULL [x]
# y       1  90             90    -2      NA    NA   NULL [y]
# zlev    1   1          0 [m]    NA      NA    NA   NULL    
# time    1   1 1981-12-31 UTC    NA POSIXct    NA   NULL    
```
reveals that `anom` now has one more missing value than expected. In previous, saved tests it would give the same value. When I rerun with `stars` from CRAN, I get the new value. Is it possible this is due to an update in a package we depend on, @mdsumner ?

**Comment by mdsumner** [comment] 2019-06-23 23:05
It seems to be a problem with RNetCDF 2.0-1, and doesn't occur with the CRAN version 1.9-1 - is that what you have installed? 

I need to look more closely, that's very unexpected, to see instability at that level, but that seems to be the problem. 

```R
f <- system.file("nc/reduced.nc", package = "stars")

## RNetCDF 1.9-1 from CRAN
rnc <- RNetCDF::open.nc(f)
sum(is.na(RNetCDF::var.get.nc(rnc, "anom")))
#[1] 4448

nc4 <- ncdf4::nc_open(f)
sum(is.na(ncdf4::ncvar_get(nc4, "anom")))
#[1] 4448

## RNetCDF 2.0-1 
## remotes::install_github("mjwoods/RNetCDF)
rnc <- RNetCDF::open.nc(f)
sum(is.na(RNetCDF::var.get.nc(rnc, "anom")))
#[1] 4449
```

**Comment by mdsumner** [comment] 2019-06-24 02:50
Ah, and it's  a change in the default of `na.mode` for `var.get.nc` is the cause, from `na.mode = 0` to `na.mode = 4`.  (previously were only modes 0, 1, 2, 3 none of which would turn that value into an NA). 

https://github.com/mjwoods/RNetCDF/pull/44

So, at position 11302 in RNetCDF 2.0-1 there is a `-1016` which is lower than the sentinel `missing_value = -999s`. 

```bash
system(sprintf("ncdump -h %s | grep anom", f))
 short anom(time, zlev, lat, lon) ;
 anom:long_name = "Daily sea surface temperature anomalies" ;
 anom:units = "degree_C" ;
 anom:add_offset = 0.f ;
 anom:scale_factor = 0.01f ;
 anom:_FillValue = -999s ;
 anom:missing_value = -999s ;
```
```R
RNetCDF::var.get.nc(rnc, "anom", na.mode = 0)[11302]
[1] -1016
> RNetCDF::var.get.nc(rnc, "anom", na.mode = 4)[11302]
[1] NA
```

We cannot get that value set to NA in previous versions afaics.

**Comment by edzer** [comment] 2019-06-24 06:53
Indeed, I was testing with
```
 RNetCDF     * 2.0-1   2019-06-03 [1] Github (mjwoods/RNetCDF@5aa1712)
```

**Comment by edzer** [comment] 2019-07-03 18:42
So, do we need to add `na.mode = 4` to all calls to `var.get.nc`?

**Comment by mdsumner** [comment] 2019-07-03 22:27
No I don't think so, this is a problem with NOAA's files and no doubt extremely rare. If anything the best outcome would be to include control over the function call, but anyone wanting that could do it themselves

**Comment by mdsumner** [comment] 2019-07-06 00:28
Actually, we might as well - I don't see any reason not to, but it will need to condition on version of RNetCDF. One thing I wanted was clarity on the process that created the reduced.nc file, just to make sure it is a problem in the original source files. Do you have that? If not I'll compare the original data.

**Comment by mdsumner** [comment] 2019-07-25 04:14
So, finally looking at this - `na.mode = 4` will be the default when RNetCDF > 1.9-1 comes out, so it's really just this test artefact that this concerns. Is there a way to condition a old-style test like this? I think we should ignore it if possible, there will be very minor drift in package outputs like this. 

Otherwise I'm happy to PR a mod where `na.mode = 0` or `na.mode = 4` based on package version, so that it's explicit. 

(It's definitely a problem with the source data, too. The advertised `anom` range is just wrong for the source of this OISST file.)

**Comment by edzer** [comment] 2019-07-25 11:56
Thanks! Since data files with these kind of problems are out there (an NOAA is, well, let's say not just a small provider) I'd vote for adding this as an option & documenting this. It's trivial to write code depending on package versions, see e.g. https://github.com/r-spatial/stars/blob/master/R/aggregate.R#L40

**Comment by mdsumner** [comment] 2019-07-25 12:37
I'm cool with the package code and versioning, but the tests is what I don't know how to do - it's just a static artefact (? comparing sink() output? ). Is it possible to do that with these old tests, or should I just create testthat tests?

Actually, I just had to write that out, that's what I'll do and we can remove this as a test mechanism.

**Comment by edzer** [comment] 2019-07-25 12:57
I'm totally fine with testthat!

**Comment by dblodgett-usgs** [comment] 2019-08-06 19:09
Note that there are lots of changes coming in RNetCDF -- most of which won't be a big deal but I found a number of minor issues over in ncmeta. Getting into some work on `stars` now and will make sure things test out ok.

**Comment by dblodgett-usgs** [comment] 2019-08-16 00:56
AFAIK the testthat tests completely cover what's tested here: https://github.com/r-spatial/stars/blob/master/tests/netcdf.R

Should we just remove the old test and close this issue?

**Comment by mdsumner** [comment] 2019-08-16 02:02
Yes thank you! (This has been niggling and I just can't get to it)

**Closed** 2019-08-16 14:26 UTC
