### ISSUE TITLE
stars2nc

### ISSUE THREAD

**Issue by fipoucat** [r-spatial/stars#240] opened 2020-01-16 10:15 UTC
Is there a way to convert stars format file to netcdf or other raster format?

**Comment by edzer** [comment] 2020-01-16 10:59
Did you have a look at `write_stars`?

**Comment by fipoucat** [comment] 2020-01-16 11:16
I am facing install error, will look at write_stars after solving this issue.

**Comment by fipoucat** [comment] 2020-01-16 15:14
this structure of stars file I am trying to put in nc.
str(mid_stars)
List of 11
 $ MeanTemperature     : num [1:395, 1:119, 1:2] NA NA NA NA NA NA NA NA NA NA ...
 $ MinTemperature      : num [1:395, 1:119, 1:2] NA NA NA NA NA NA NA NA NA NA ...
 $ MaxTemperature      : num [1:395, 1:119, 1:2] NA NA NA NA NA NA NA NA NA NA ...
 $ Precipitation       : num [1:395, 1:119, 1:2] 0 0 0 0 0 0 0 0 0 0 ...
 $ MeanRelativeHumidity: num [1:395, 1:119, 1:2] NA NA NA NA NA NA NA NA NA NA ...
 $ MinRelativeHumidity : num [1:395, 1:119, 1:2] NA NA NA NA NA NA NA NA NA NA ...
 $ MaxRelativeHumidity : num [1:395, 1:119, 1:2] NA NA NA NA NA NA NA NA NA NA ...
 $ Radiation           : num [1:395, 1:119, 1:2] NA NA NA NA NA NA NA NA NA NA ...
 $ WindSpeed           : num [1:395, 1:119, 1:2] 3.65 3.64 3.62 3.6 3.58 ...
 $ WindDirection       : num [1:395, 1:119, 1:2] 41.6 41.2 40.9 40.6 40.5 ...
 $ PET                 : num [1:395, 1:119, 1:2] NA NA NA NA NA NA NA NA NA NA ...
 - attr(*, "dimensions")=List of 3
  ..$ x   :List of 7
  .. ..$ from  : num 1
  .. ..$ to    : int 395
  .. ..$ offset: num 289417
  .. ..$ delta : num 902
  .. ..$ refsys: chr "+init=epsg:32628 +proj=utm +zone=28 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0"
  .. ..$ point : logi NA
  .. ..$ values: NULL
  .. ..- attr(*, "class")= chr "dimension"
  ..$ y   :List of 7
  .. ..$ from  : num 1
  .. ..$ to    : int 119
  .. ..$ offset: num 1542095
  .. ..$ delta : num -922
  .. ..$ refsys: chr "+init=epsg:32628 +proj=utm +zone=28 +datum=WGS84 +units=m +no_defs +ellps=WGS84 +towgs84=0,0,0"
  .. ..$ point : logi NA
  .. ..$ values: NULL
  .. ..- attr(*, "class")= chr "dimension"
  ..$ time:List of 7
  .. ..$ from  : num 1
  .. ..$ to    : int 2
  .. ..$ offset: POSIXct[1:1], format: "2019-03-15"
  .. ..$ delta : 'difftime' num 137
  .. .. ..- attr(*, "units")= chr "days"
  .. ..$ refsys: chr "POSIXct"
  .. ..$ point : logi NA
  .. ..$ values: NULL
  .. ..- attr(*, "class")= chr "dimension"
  ..- attr(*, "raster")=List of 3
  .. ..$ affine     : num [1:2] 0 0
  .. ..$ dimensions : chr [1:2] "x" "y"
  .. ..$ curvilinear: logi FALSE
  .. ..- attr(*, "class")= chr "stars_raster"
  ..- attr(*, "class")= chr "dimensions"
 - attr(*, "class")= chr "stars"

**Comment by dblodgett-usgs** [comment] 2020-01-16 15:26
I'm not aware of a general writer for XYT NetCDF data in R. I wrote one for station-time data over in `ncdfgeom` and could see crafting one for `stars` but it would have to be very opinionated and would likely only have limited utility without a ton of work to generalize it. 

I think your best bet is going to be to create a template dataset with CDL and the `ncgen` command line utility then write your `stars` data into that file with `rnetcdf`.

**Comment by bart1** [comment] 2020-11-09 07:17
Some what related I'm running into similar issues writing stars object. I generate stars objects on a cluster with lots of memory. I would like to save these and use them locally to explore and visualize. I can't find file formats that `write_stars` support that retain the dimensions well (XYT in my case but i think the problem is more general). Currently I resort to writing an `rds` file but the disadvantage if this approach is that the data can not be loaded in other programs and more so I run into memory issued on my local machine as I can't profit from the `stars_proxy` optimizations. I think writing to `hdf5` or `netcdf` while retaining dimensions and attributes would be great.

**Comment by alexyshr** [comment] 2020-11-09 07:33
I was thinking in something similar to a [worlfile](https://en.m.wikipedia.org/wiki/World_file) plus a normal NetCDF file to save `proxy_stars` objects. In some cases the additional metadata needed for stars georeferencing (for instance the dimension value) imply difficulties to execute some R functions (for instance `dplyr` related). Actually, my idea is to work with text files to save metadata and operations while creating and processing `proxy_stars` objects. As I am not an expert in the internal stars data-mode and implementationl, I just trigger this idea as a question for the experts.

**Comment by edzer** [comment] 2021-05-05 20:12
Closing in favor of #419

**Closed by edzer** 2021-05-05 20:12 UTC
